In [2]:
import pandas as pd
import numpy as np

#pandas series

In [4]:
data = pd.Series([1.2,3,3,6])
data

0    1.2
1    3.0
2    3.0
3    6.0
dtype: float64

In [6]:
type(data)

pandas.core.series.Series

In [7]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
#explicit indexing
data_explict = pd.Series([1.2,3,4,5], index = ['a','b','c','d'])

In [10]:
data_explict.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [11]:
#values attribute
data.values

array([1.2, 3. , 3. , 6. ])

In [12]:
data

0    1.2
1    3.0
2    3.0
3    6.0
dtype: float64

In [13]:
data[0]#first item in the series

np.float64(1.2)

In [14]:
#first 3 elements
data[0:3]

0    1.2
1    3.0
2    3.0
dtype: float64